# Generated by Django 4.2.1 on 2023-06-04 15:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freeboard', '0004_recommended_freeboardpost_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommended_FreeboardPost',
            new_name='Recommended_FreePost',
        ),
    ]
