# Generated by Django 4.2.1 on 2023-05-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkmap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='name',
            new_name='title',
        ),
    ]
