# Generated by Django 4.2.1 on 2023-06-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boastboard', '0002_boastpost_liked_num_recommended_boastpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastpost',
            name='author',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
