# Generated by Django 4.2.1 on 2023-06-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketboard', '0002_recommended_marketpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketpost',
            name='liked_num',
            field=models.IntegerField(default='0'),
        ),
    ]
