# Generated by Django 4.2.1 on 2023-06-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketboard', '0003_marketpost_liked_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketpost',
            name='author',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
