# Generated by Django 4.2.1 on 2023-06-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketboard', '0005_recommended_freepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommended_FreePost',
        ),
    ]
