# Generated by Django 4.2.1 on 2023-05-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('open_hours', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('visitor_review', models.CharField(max_length=20)),
                ('blog_review', models.CharField(max_length=20)),
                ('website', models.URLField()),
            ],
        ),
    ]
