# Generated by Django 4.2.1 on 2023-05-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storemap', '0005_alter_store_blog_review_alter_store_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='store',
            name='longitude',
        ),
    ]
