# Generated by Django 4.2 on 2023-05-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('email_address', models.TextField(max_length=100)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('reservation_time', models.TimeField(auto_now_add=True)),
                ('dog_type', models.CharField(max_length=20)),
            ],
        ),
    ]
