# Generated by Django 4.2.1 on 2023-05-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gptjango', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
