# Generated by Django 4.2.1 on 2023-05-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doglist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doglist',
            new_name='Dog',
        ),
    ]
