# Generated by Django 4.2.1 on 2023-05-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doglist', '0002_rename_doglist_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='img_src',
            field=models.CharField(max_length=300),
        ),
    ]
