# Generated by Django 4.2.1 on 2023-06-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doglist', '0004_alter_dog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='kind_size',
            field=models.CharField(default='', max_length=100),
        ),
    ]
