# Generated by Django 4.2.1 on 2023-06-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='size',
            field=models.CharField(default='', max_length=255),
        ),
    ]
