# Generated by Django 4.2.1 on 2023-06-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default='2023-06-06'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='dog',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
