# Generated by Django 4.2.1 on 2023-06-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewboard', '0008_recommended_reviewpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpost',
            name='liked_num',
            field=models.IntegerField(default='0', max_length=50, null=True),
        ),
    ]
